### ISSUE TITLE
Update to new FreeCAD AddonManager metadata schema

### ISSUE THREAD

**Issue by luzpaz** [FrontISTR/FEM_FrontISTR#3]
https://github.com/FreeCAD/FreeCAD-addons/issues/200

**Comment by luzpaz** [comment]
ping @kinagaki

**Comment by luzpaz** [comment]
bump

**Comment by kinagaki** [comment]
In progress...

**Comment by chikasuiro** [comment]
@luzpaz
I wrote the `package.xml` and now it can be seen from pull request.
https://github.com/FrontISTR/FEM_FrontISTR/pull/7/files
I made it according to the wiki, but since I'm not so familiar with that file, **would you check contents are correct?**
If it has no problem, @kinagaki will merge the request.
